### ISSUE TITLE
Discord update break this I think

### ISSUE THREAD

**Issue by tuwuna** [LuckFire/AMOLED-Cord#1]
![ ](https://cdn.discordapp.com/attachments/686387177902702626/769147878013927424/unknown.png)

**Comment by tuwuna** [comment]
And profile page too

**Comment by LuckFire** [comment]
what os are you on? seems like it either may be using different elements compared to windows or i haven't gotten the update yet

**Comment by HooferDevelops** [comment]
can confirm this happens on Windows 10 as well.

**Comment by LuckFire** [comment]
oh boy

**Comment by LuckFire** [comment]
nothing is broken, it looks like the import for the source is missing? reinstall the theme. if that doesn't work lmk

**Comment by tuwuna** [comment]
Yes, my bad

**Comment by LuckFire** [comment]
Glad the issue is fixed :>

**Comment by tuwuna** [comment]
I think this time it is actually broken after update, I double checked my files a few time
Version: Canary 74397 (ed4874e)

**Comment by tuwuna** [comment]
Seems like they rolled back.
