### ISSUE TITLE
Search options are broken

### ISSUE THREAD

**Issue by zroncarij** [LuckFire/amoled-cord#12]
No longer amoled dark

**Comment by Poirot12345T** [comment]
same issue;
Stable 100054 (69f0658)
BetterDiscord 1.2.1

**Comment by amxmu** [comment]
Wanting to keep this thread alive as idk what happened to the dev but this issue is still present.

**Comment by Poirot12345T** [comment]
Maybe we can fork it open a pull request, until pulled, use the fork instead (there's one problem, that I don't know CSS to make it work)

**Comment by LuckFire** [comment]
please be sure to check [this issue](https://github.com/LuckFire/amoled-cord/issues/14) out, as i'm not going to prioritize maintainability of the theme currently, as i'm working on a rewrite for this.

**Comment by LuckFire** [comment]
I've fixed this in v2. Please make sure you redownload the theme entirely.
