### ISSUE TITLE
Option highlighting is hard to see

### ISSUE THREAD

**Issue by Tancred423** [LuckFire/amoled-cord#13]
If you select something like an emote from the suggestions, the highlighted line is hard to see. I also noticed that this depends on what monitor im using. On my main monitor it is "okay" to see, but on my 2nd monitor I can't really see the highlight at all.

I found out that it uses the "--background-primary" color variable, so I can't change that easily on my side without having the rest of the theme look bad.

An example GIF while cycling through some suggested emotes:
![image](https://tanc.red/share/2021_11_02_DFf7OSwZom.gif)

Would it be possible to make this a bit lighter, please?

_Thanks in advance and good job on this awesome theme 😎_

**Comment by LuckFire** [comment]
I've fixed this in v2. Please make sure you redownload the theme entirely.
