### ISSUE TITLE
Settings Icon spacing is not working

### ISSUE THREAD

**Issue by amxmu** [LuckFire/amoled-cord#15]
![download](https://user-images.githubusercontent.com/92172841/143960196-7c881761-dc69-46f1-9946-746e5e1855bc.png)

Settings icons are not spaced properly. After turning off theme, the spacing goes back to normal like so:
![image](https://user-images.githubusercontent.com/92172841/143960259-aca052b7-50c3-4872-85dd-83d8a184dc4b.png)

I tested with theme on and plugins off as well as removing custom css and the spacing is still weird. Unsure if this is an issue on my side or not.

**Comment by LuckFire** [comment]
a

**Comment by LuckFire** [comment]
im assuming you're using powercord or vizality

do you have any css that adds icons to settings?

**Comment by amxmu** [comment]
I did remove the import css for Settings icons (from BetterDiscord) and that removes the custom icons and makes them all one icon:
![image](https://user-images.githubusercontent.com/92172841/143960655-91b51e73-0183-47e6-963d-cecf9dd5d7db.png)

**Comment by LuckFire** [comment]
one sec

**Comment by Loremly** [comment]
Sometimes you gotta close the door to open the window.

**Comment by LuckFire** [comment]
you'll have to redownload the theme, but it should work fine now

**Comment by amxmu** [comment]
![image](https://user-images.githubusercontent.com/92172841/143960839-4ddf7541-db53-4078-81b3-bc26c59ca046.png)
Also is this part supposed to be unthemed?

**Comment by LuckFire** [comment]
ill have to theme that later as i somehow missed it

**Comment by amxmu** [comment]
spacing is fixed! and I'll look out for the other update! thanks

**Comment by LuckFire** [comment]
awesome, closing this issue now
