### ISSUE TITLE
Is it possible to remove the out of date?

### ISSUE THREAD

**Issue by Ray-MRQ** [LuckFire/amoled-cord#16]
Hi,

Sorry if this isn't the correct way but wondering if I can stick with the older version of AMOLED-cord without getting the popup to update?

The two shades of black is slightly annoying for me and much preferred the older one over the new one.

**Comment by LuckFire** [comment]
```css
#app-mount::after {
     content: none;
}
```
however, i plan on removing that file in a few days, so make sure you make a fork of this repo and change the import to your own link.

**Comment by Ray-MRQ** [comment]
Thanks, just tried it, and worked, I'll just keep a copy of it locally anyways so all good.
