### ISSUE TITLE
Please remove the persistent update notification

### ISSUE THREAD

**Issue by xjarlie** [LuckFire/amoled-cord#19]
![image](https://user-images.githubusercontent.com/49068203/144000603-488e9d1b-d4d7-4130-bb92-e2536f579a3a.png)
Personally, I prefer the old version of the theme for use with BetterDiscord, and I would like to be able to without seeing this annoying notification that just won't go away.

**Comment by xjarlie** [comment]
nvm sorry this is a duplicate

**Comment by LuckFire** [comment]
removed the notification from the old version, but please note that i will no longer be updating it (so if something isn't themed, that's all you).

however, if you could still give me some feedback as to why you prefer the old version (i.e. what should change back, what should be different, etc.) i'd seriously appreciate it :>
