### ISSUE TITLE
Light mode support

### ISSUE THREAD

**Issue by pythonmcpi** [LuckFire/AMOLED-Cord#2]
# Describe the Issue
I usually use light mode and when I first put the theme on some parts of the menu were a bit weird. The themes coming soon picture still used a white background, and I couldn't see some options in the Appearance tab. Switching to dark mode fixes everything so it isn't just me/my current snippets.

# How to Reproduce
Turn on light mode in appearances and then turn on the theme
You might need to disable other themes

**Comment by LuckFire** [comment]
The theme is meant to be used in darkmode only. Later on I'll add a warning for using lightmode with the theme.
