### ISSUE TITLE
Color Bugs

### ISSUE THREAD

**Issue by TheHunter1234** [LuckFire/amoled-cord#21]
I have been having these bugs ever since the new update. How would this be fixed? Is this a me issue or a bug in the theme?
![image](https://user-images.githubusercontent.com/69104450/144342272-f5734529-a345-4a00-9cf7-5494a28f41b4.png)

**Comment by LuckFire** [comment]
Please make sure:
- You don't have any conflicting CSS
- You're on the newest update

If it still persists, please give the following information:
1. What Discord build you're on (such as Stable, Public Test Build, or Canary).
2. What client mod you're using.
3. More information of where the color bugs are coming from, such as if it's part of a plugin or built-in to Discord. If a plugin, what plugin? If not, where specifically in Discord?

**Comment by TheHunter1234** [comment]
I do not have any conflicting CSS that would affect the bug. I am on the newest update for BetterDiscord, Discord, and the theme.

I am using Stable, BetterDiscord, and it is at the top of the member list on Discord, no plugin.
![image](https://user-images.githubusercontent.com/69104450/144366050-38df403e-b1e6-4997-94e7-ddde35a11447.png)

**Comment by LuckFire** [comment]
fixed in v2.1.3
