### ISSUE TITLE
Color bug

### ISSUE THREAD

**Issue by RadNotRed** [LuckFire/amoled-cord#23]
Color error in booster page
![image](https://user-images.githubusercontent.com/80015713/147020954-190e891f-a0c3-4988-947e-3e3498bb2f17.png)

**Comment by RadNotRed** [comment]
Another bug in the event info and interested member page
![image](https://user-images.githubusercontent.com/80015713/147021700-91cb26be-6216-46d1-b659-9183191e9323.png)

**Comment by LuckFire** [comment]
:+1: fixed

**Comment by RadNotRed** [comment]
thank you

**Comment by RadNotRed** [comment]
didnt fix this one for me, at least on my end

![image](https://user-images.githubusercontent.com/80015713/147308243-27b7219f-54f1-4361-8e9b-ede97ffea5bf.png)

**Comment by LuckFire** [comment]
fixed
