### ISSUE TITLE
Recent Client Update Breaks Theme

### ISSUE THREAD

**Issue by RadNotRed** [LuckFire/amoled-cord#27]
hi its me again the new discord canary / development update literally broke everything 
![image](https://user-images.githubusercontent.com/80015713/148631938-b5bfd9f1-16a8-4f54-a58b-b2f911e4248a.png)

**Comment by LuckFire** [comment]
I'll have to wait before I do anything. Have to wait and make sure Discord won't change every class again as well as wait for the same change to be pushed to other builds.

**Comment by hugh-braico** [comment]
I came here to see what was going on, thanks for keeping this theme maintained, it's very much appreciated.

**Comment by SuperMarioROCKS** [comment]
mario likes this theme

**Comment by RadNotRed** [comment]
> I'm going to wait a bit before doing anything, just to be sure that Discord doesn't break multiple things again where I have to update almost the entire theme **again**. Also, only canary users are affect currently, which probably isn't a majority of users. I would like to wait til these changes are out on other builds as well.

all good! thanks!

**Comment by psychedelic-fox** [comment]
from the Powercord Discord channel:

> **Many of my plugins and themes are broken**
> Discord released an update that broke many plugins and re-rolled many class names, which broke many themes. The solution is to wait for an update from the plugin and theme devs.

**Comment by amxmu** [comment]
New update broke the theme on Stable and PTB too it seems

**Comment by RadNotRed** [comment]
> 
works on stable for me

**Comment by elijaholmos** [comment]
stable is broken on my end as well

**Comment by LuckFire** [comment]
reeeeeee

I'll get to updating it sometime this week

**Comment by LuckFire** [comment]
UPDATE: I'm currently in the process of fixing it, it'll either be ready by later today or tomorrow.

**Comment by LuckFire** [comment]
> im going to try to fix some stuff in about an hour and a half, ill update if I can get it working 100%

Feel free to, but I planned on changing some things (since I'm redoing the entire theme).

**Comment by RadNotRed** [comment]
> > im going to try to fix some stuff in about an hour and a half, ill update if I can get it working 100%
> 
> Feel free to, but I planned on changing some things (since I'm redoing the entire theme).

oh god 
well I'm excited to see the technical v3 of it

**Comment by LuckFire** [comment]
It'll be labeled as v3 yea, but don't expect too much to change besides minor color adjustments.

**Comment by RadNotRed** [comment]
if you're desperate for a working amoledcord and can't wait for v3 just `git clone https://github.com/RadNotRed/amoled-cord` and it should work

**Comment by RadNotRed** [comment]
> It'll be labeled as v3 yea, but don't expect too much to change besides minor color adjustments.
> 
> Also, all the color issues you've reported will be fixed in this version.

sounds good , thanks

**Comment by Goodgamer78** [comment]
broken on stable release now. rip

**Comment by RadNotRed** [comment]
> broken on stable release now. rip

wait for v3 should be done soon

**Comment by JJ-VP** [comment]
@LuckFire Idk how much you plan on changing in said V3 but I have updated the theme to the new classes, want me to make a PR or are you already working on it?

**Comment by gamingchairnig** [comment]
> @LuckFire Idk how much you plan on changing in said V3 but I have updated the theme to the new classes, want me to make a PR or are you already working on it?

could u upload it thanks

**Comment by JJ-VP** [comment]
> could u upload it thanks

[I have a fork of the theme](https://github.com/JJ-VP/amoled-cord)

**Comment by andrewsmyname** [comment]
> UPDATE: I'm currently in the process of fixing it, it'll either be ready by later today or tomorrow.

Thank you very much, your work is greatly appreciated! <3

**Comment by LuckFire** [comment]
> @LuckFire Idk how much you plan on changing in said V3 but I have updated the theme to the new classes, want me to make a PR or are you already working on it?

Appreciate it, but I'm already working on it and almost have it done. I apologize for taking so long, since this is something I do whenever I have motivation to actually do it. I'll have the stuff pushed out by today.

**Comment by RadNotRed** [comment]
> > @LuckFire Idk how much you plan on changing in said V3 but I have updated the theme to the new classes, want me to make a PR or are you already working on it?
> 
> Appreciate it, but I'm already working on it and almost have it done. I apologize for taking so long, since this is something I do whenever I have motivation to actually do it. I'll have the stuff pushed out by today.

ur good bro, take your time

**Comment by LuckFire** [comment]
pushed, give it a bit to update.

**Comment by ninox14** [comment]
how do you install it for better_discord  ? 
do i have to compile it myself ?

**Comment by LuckFire** [comment]
> how do you install it for better_discord ? do i have to compile it myself ?

it should automatically just update if you have it, unless you have a version older than 2.0.0, then you can download it [here](https://github.com/LuckFire/amoled-cord/releases/download/temp-bd-download/AMOLED-Cord.theme.css)

**Comment by JJ-VP** [comment]
😄 Looks good. Everything seems to be spot on.

**Comment by amxmu** [comment]
The theme colors everything properly but when I use the "Hide member list" custom CSS with the theme -- the member list when hovered over becomes transparent.
![image](https://user-images.githubusercontent.com/92172841/149231353-0ab9e718-ca22-43cc-8aea-066dafc86d07.png)

/* Hide member list */
:root {
  --hover-animation-speed: 0.35s;
  --seperator-color: var(--seperator-color);
}
.membersWrap-3NUR2t {
  min-width: unset;
  width: 50px;
  justify-content: right;
}
.members-3WRCEx {transition: transform var(--hover-animation-speed);}
.membersWrap-3NUR2t:hover .members-3WRCEx {transform: translateX(-190px);}
.membersWrap-3NUR2t .membersGroup-2eiWxl::after {
  content: '';
  width: 30px;
  height: 2px;
  border-radius: 50px;
  background: unset;
  background-color: var(--seperator-color);
  position: absolute;
  left: -36px;
  top: 29px;
  margin-left: 0px;
}
.membersWrap-3NUR2t .members-3WRCEx .member-2gU6Ar {
  background-color: unset;
  margin-left: 0px;
  transition: margin-left var(--hover-animation-speed);
}
.membersWrap-3NUR2t:hover .members-3WRCEx .member-2gU6Ar {margin-left: 8px;}
.membersWrap-3NUR2t:hover .membersGroup-2eiWxl {transform: translateX(-6px);}
.membersWrap-3NUR2t .membersGroup-2eiWxl {
  cursor: default;
  transform: translateX(45px);
  transition: transform var(--hover-animation-speed);
  overflow: visible;
}

**Comment by N72826** [comment]
![image](https://user-images.githubusercontent.com/21070431/149234156-eef547ca-b3fe-45b4-b7bc-62b19961bd69.png)
![image](https://user-images.githubusercontent.com/21070431/149234207-1cd5ba70-3a23-42cd-a5f5-7dabe289f0e7.png)
![image](https://user-images.githubusercontent.com/21070431/149234234-bb6e5737-c047-4aa7-ba87-3a7984bb2e9d.png)
as you can see, there are still some things that have not been changed. I appreciate you for maintaining this still, it is a must have addition.

**Comment by RadNotRed** [comment]
thread closed. pls make your own issues instead of spamming my inbox :(

**Comment by LuckFire** [comment]
replying to this so you all know that i've seen these issues, and ill push something out soon to fix and adjust things

**Comment by JayMehta9292** [comment]
yo @LuckFire how long will it take to fix this broken theme?

**Comment by LuckFire** [comment]
> yo @LuckFire how long will it take to fix this broken theme? 

it is quite literally fixed, redownload if it's not working still.

**Comment by JayMehta9292** [comment]
> > yo @LuckFire how long will it take to fix this broken theme?
> 
> it is quite literally fixed, redownload if it's not working still.

thank man redownloaded it and its fixed

**Comment by JayMehta9292** [comment]
@LuckFire can you add me on discord? My discord tag is  Jay Mehta#9292 

i have a suggestion for you if you like then add it

**Comment by RadNotRed** [comment]
STOP THIS THREAD IS CLOSED

**Comment by LuckFire** [comment]
> @LuckFire can you add me on discord? My discord tag is Jay Mehta#9292
> 
> i have a suggestion for you if you like then add it

I suggest creating another issue or just dming me on Discord, my DMs are open if you're in the powercord or bd server. Im closing this now to prevent further replies.
