### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by ThunderUwUr** [LuckFire/amoled-cord#28]
![image](https://user-images.githubusercontent.com/97650779/149258914-ea389c87-6487-464d-8f32-857807884258.png)

the friendlist background color changed.

**Comment by N72826** [comment]
same. he's working on fixing everything as we create issue threads, I can only hope we are expediting the process by pointing out all of the areas he may potentially miss. refer to #27

**Comment by LuckFire** [comment]
Please redownload the theme [here](https://github.com/LuckFire/amoled-cord/releases/download/temp-bd-download/AMOLED-Cord.theme.css) first, and see if the issue still persists.

**Comment by N72826** [comment]
> Please redownload the theme [here](https://github.com/LuckFire/amoled-cord/releases/download/temp-bd-download/AMOLED-Cord.theme.css) first, and see if the issue still persists.
![image](https://user-images.githubusercontent.com/21070431/149271501-be94c1e1-4f1f-4492-9a8f-9a84a3947653.png)
![image](https://user-images.githubusercontent.com/21070431/149271569-a501ab74-a2b0-41ab-bcf7-bd9c0a12d312.png)
nice man! definitely closer. embeds are still fucked, the outer frame of discord is still light, the send button plugin is white as hell, when you click on a user the popup seems lighter but maybe I'm wrong and that seems to be it. you fixed the friends activity tab already, maybe the search bar also?

**Comment by LuckFire** [comment]
> the outer frame of discord is still light
Please elaborate a bit on this one

> the send button plugin is white as hell
will have to look into this, doesnt happen on my end.

**Comment by N72826** [comment]
ah sorry my bad, the outer frame as in the color of the side bar containing all of the servers.

**Comment by LuckFire** [comment]
that's intentional, has always been like that

**Comment by N72826** [comment]
> that's intentional, has always been like that since v2

apologies, didn't notice. I meant the message box not the search bar btw.

**Comment by LuckFire** [comment]
ohh you're using a plugin, that may just be the plugin itself and not the theme.
discord recently added a send message button, just right click on the message bar and you can enable it
![image](https://user-images.githubusercontent.com/39076891/149272665-2a0378f5-8abe-4c9b-8001-01bee3840a50.png)

**Comment by N72826** [comment]
> ohh you're using a plugin, that may just be the plugin itself and not the theme. discord recently added a send message button, just right click on the message bar and you can enable it ![image](https://user-images.githubusercontent.com/39076891/149272665-2a0378f5-8abe-4c9b-8001-01bee3840a50.png)

wtffff thank you so much.

**Comment by LuckFire** [comment]
i'll adjust the message bar next update i push, glad to of helped. im going to close this issue now, but if you have any other issues feel free to comment on this or reopen it!

**Comment by N72826** [comment]
![image](https://user-images.githubusercontent.com/21070431/149272772-1f39fb33-6915-4042-9a37-5c56974e0fb3.png)
plugins are still light, and in account settings, still light but I assume that's the same color used in user popouts so I already mentioned that.

**Comment by LuckFire** [comment]
i'll go around as well and make a few things darker, cause some things are lighter than they should be next update

**Comment by N72826** [comment]
> i'll go around as well and make a few things darker, cause some things are lighter than they should be next update

you are amazing. It's definitely usable now though, no reason to complain. I am satisfied. thanks again dude.
