### ISSUE TITLE
Issue with "Hide Member List" custom CSS

### ISSUE THREAD

**Issue by amxmu** [LuckFire/amoled-cord#29]
https://github.com/LuckFire/amoled-cord/issues/27#issuecomment-1011499656

I originally made this comment on another issue. Bringing it up again in the event it wasn't resolved.

I don't have any new custom CSS I can use nor do I know why AMOLEDcord breaks the member list with this custom css.

Here is the CSS I have in my Custom CSS for this:

/* Hide member list */
:root {
  --hover-animation-speed: 0.35s;
  --seperator-color: var(--seperator-color);
}
.membersWrap-3NUR2t {
  min-width: unset;
  width: 50px;
  justify-content: right;
}
.members-3WRCEx {transition: transform var(--hover-animation-speed);}
.membersWrap-3NUR2t:hover .members-3WRCEx {transform: translateX(-190px);}
.membersWrap-3NUR2t .membersGroup-2eiWxl::after {
  content: '';
  width: 30px;
  height: 2px;
  border-radius: 50px;
  background: unset;
  background-color: var(--seperator-color);
  position: absolute;
  left: -36px;
  top: 29px;
  margin-left: 0px;
}
.membersWrap-3NUR2t .members-3WRCEx .member-2gU6Ar {
  background-color: unset;
  margin-left: 0px;
  transition: margin-left var(--hover-animation-speed);
}
.membersWrap-3NUR2t:hover .members-3WRCEx .member-2gU6Ar {margin-left: 8px;}
.membersWrap-3NUR2t:hover .membersGroup-2eiWxl {transform: translateX(-6px);}
.membersWrap-3NUR2t .membersGroup-2eiWxl {
  cursor: default;
  transform: translateX(45px);
  transition: transform var(--hover-animation-speed);
  overflow: visible;
}

**Comment by LuckFire** [comment]
should be fixed, sorry it took so long.
