### ISSUE TITLE
Nitro areas are not themed.

### ISSUE THREAD

**Issue by SomeAspy** [LuckFire/amoled-cord#3]
![image](https://user-images.githubusercontent.com/33640860/104657704-6e8d5400-568f-11eb-933f-d66608957fd8.png)
![image](https://user-images.githubusercontent.com/33640860/104657728-7b11ac80-568f-11eb-8f26-968d656ce0e1.png)

**Comment by LuckFire** [comment]
would theme the one in settings but i dont have access to that one
as for the one for when someone gifts, that'll be done soon:tm: when theme source is revamped

**Comment by LuckFire** [comment]
should be themed now!
