### ISSUE TITLE
latest Canary breaks theme

### ISSUE THREAD

**Issue by psychedelic-fox** [LuckFire/amoled-cord#31]

**Comment by LuckFire** [comment]
this has already been fixed, reinstall the theme.

**Comment by psychedelic-fox** [comment]
it has not.

https://i.imgur.com/QFfwXIH.png

Canary ver. `aeec87b`
Theme ver. `d4ff06c`

**Comment by LuckFire** [comment]
What client mod are you using?

**Comment by psychedelic-fox** [comment]
> ~What client mod are you using?~ i am blind
> 
> Doesn't make sense on why it's not working, I just reinstalled the theme myself and it's working perfectly fine. Are there any errors in console relating to the theme?

not that I can see, there's one error that may be a possibility:

https://i.imgur.com/0tN783G.png

I feel like that'd be my client mod acting up, if it's the cause of the theme not loading.

**Comment by LuckFire** [comment]
It's either that, or somehow you're cloning a version without the `./src/theme` folder.

Can you show me what's inside the `src` folder of the theme?

**Comment by psychedelic-fox** [comment]
> It's either that, or somehow you're cloning a version without the `./src/theme` folder.
> 
> Can you show me what's inside the `src` folder of the theme?

sure, [here you go](https://i.imgur.com/Exv4GnE.png). I apologize for the late replies.

**Comment by LuckFire** [comment]
Interesting, the folder is there so I have no clue why it's not working properly.
