### ISSUE TITLE
Theme is semi broken

### ISSUE THREAD

**Issue by proudmuslim-dev** [LuckFire/AMOLED-Cord#4]
Friends area is the normal gray, and the same is true for the reactions menu and the upload menu

**Comment by proudmuslim-dev** [comment]
This is due to a discord update

**Comment by hairyfred** [comment]
Can also confirm this

**Comment by LuckFire** [comment]
most likely an issue with importing the source, not really a discord end. if it happens again, reload your discord. if that doesn't fix, reinstall the theme.
