### ISSUE TITLE
Friends Tab Grey

### ISSUE THREAD

**Issue by Godly-Avenger** [LuckFire/amoled-cord#40]
For some reason, the friends tab in Discord is now gray. I think it might have something to do with a recent update or something like that because it wasn't like this a couple days ago.
![image](https://user-images.githubusercontent.com/74989919/175792279-59a390dd-084d-4b78-9dc7-7c08c356f1b4.png)

**Comment by LuckFire** [comment]
Old issue, but this should be resolved in the newest version.
