### ISSUE TITLE
Little Modif

### ISSUE THREAD

**Issue by Nawaaak** [LuckFire/amoled-cord#42]
Hey, 
I would like to know, if its possible to change the color when u are mentionned by someone. This orange piss me off. 
Thank u for reading me. 
![image_2022-08-17_150738534](https://user-images.githubusercontent.com/111438166/185142056-995bcaa0-3ccd-4029-a18a-3db2caf85a07.png)

**Comment by LeafyLuigi** [comment]
learn css lmao

**Comment by Loremly** [comment]
change the color of these variables `--background-mentioned --background-mentioned-hovered`
