### ISSUE TITLE
Theme Repo does not pick up updates

### ISSUE THREAD

**Issue by auroraisluna** [LuckFire/amoled-cord#46]
I realized I am running a very old version of the theme (due to the many discord css updates) but on theme repo the 'source' is from 2021: https://github.com/LuckFire/amoled-cord/blob/d201810b52483c8f108f1c4ea355f6f5c34cb054/src/support/betterdiscord/AMOLED-Cord.theme.css (when clicking on the source button)
![image](https://user-images.githubusercontent.com/98479040/199367289-fb571b0b-ec7b-4dba-9d89-84de1a51ea9a.png)

I don't know if this is a themerepo issue (doubt it but could be) or some miss configuration :)

**Comment by LuckFire** [comment]
Dunno what client mod this is, but not an issue with the repo 👍

**Comment by Loremly** [comment]
pretty sure this is goosemods store but goosemod is gone :/ so idk

**Comment by LuckFire** [comment]
I assumed that but I had the same thought so I wasn't sure lol

**Comment by auroraisluna** [comment]
No, this is from DevilBro's BD plugin. https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/ThemeRepo/
Since the plugin is listed here: https://betterdiscord.app/themes?filter=amoled-cord it is also listed in the repo. 

It can be argued if this is a issue with a repo or the plugin, but since all other themes have version control (which reloads the theme and updates the css) and 'update' and work fine with it, I think this is a repo issue 🙂

**Comment by LuckFire** [comment]
Ohh if it's a DB plugin, it's most likely getting it from the website, so yes it is probably a repo issue because the site isn't picking up the new theme.css file. Once I rework AMOLED-cord tho it'll most likely be fixed, however I'll reopen this issue and leave it opened til that's done 👍

**Comment by vvirtues** [comment]
> Once I rework AMOLED-cord tho it'll most likely be fixed

ETA for the rework?

**Comment by LuckFire** [comment]
Whenever a "good" client mod works, such as Replugged. I could use BetterDiscord, but I'd have to figure out a way to do stuff in the structure that I was before which I don't think I can easily do.

**Comment by LuckFire** [comment]
i did not mean to close that LMAO

**Comment by LuckFire** [comment]
This should be fixed now.
