### ISSUE TITLE
Purple bar under text input

### ISSUE THREAD

**Issue by olivierpilotte** [LuckFire/amoled-cord#5]
I'm not sure if it's due to a Discord update, but since a couple days there's a purple bar when focusing the text input.

![underline](https://user-images.githubusercontent.com/1024274/114737859-6c31a900-9d15-11eb-8871-5be35f9487bb.png)

**Comment by LuckFire** [comment]
if you'd like to disable this bar, go into the root file (located in `./src/_root.scss/`) and change the --display-height variable to 0 or none (if you have OCD and the rounding on the bottom not being matched with the top annoys you, you can set the --border-radius variable to 6px)
