### ISSUE TITLE
Hard to view spoilered text.

### ISSUE THREAD

**Issue by Goomboi** [LuckFire/amoled-cord#6]
The spoiler text blends in with the background slightly, making it difficult to see whether or not it's a spoiler or just blank text. Make it so that the color is brighter.
![image](https://user-images.githubusercontent.com/69328615/115097809-8e7c2000-9ee9-11eb-988c-56ea62eeef7e.png)

**Comment by Goomboi** [comment]
Closing this to send it to the theme source repo.

**Comment by LuckFire** [comment]
also, posting it on this repo was fine as it's nothing to do with theme source
