### ISSUE TITLE
 the theme is not completely dark

### ISSUE THREAD

**Issue by gabrielgtav99** [LuckFire/amoled-cord#61]
I opened discord today and noticed that the theme is not the same as before, with some parts in black almost gray

![Screenshot_227](https://github.com/LuckFire/amoled-cord/assets/46336038/6bcf3040-5112-4afd-872c-540991a6e9b9)
![Screenshot_228](https://github.com/LuckFire/amoled-cord/assets/46336038/2d1e3103-287a-422b-8182-b21bd30989bf)
![image](https://github.com/LuckFire/amoled-cord/assets/46336038/8dee783b-ba6f-420e-a780-81915327c514)

**Comment by LuckFire** [comment]
Fixed in #32
