### ISSUE TITLE
Update the theme according to Discord's major update

### ISSUE THREAD

**Issue by Infisrael** [LuckFire/amoled-cord#66]
For context, Discord recently pushed a major update which broke all themes and many plugins.

**Comment by SpeedyFolf** [comment]
It looks correct for me. Is that not what the last 5 commits were about?

**Comment by LuckFire** [comment]
All of the classes *should* be updated. If some places were missed, I'd appreciate screenshots of them..

**Comment by Infisrael** [comment]
![Discord_lsncEe0x7r](https://github.com/LuckFire/amoled-cord/assets/73630497/af6ede25-3921-4b71-992c-cb959a7d6cae)

**Comment by LuckFire** [comment]
Thanks, would've appreciated that if it was provided alongside the issue being opened. I'll see if i can get this fixed soon; Discord keeps booting me out whenever I open inspect so I can't do much atm (I saw a few other *new* areas that could be themed as well).

**Comment by Infisrael** [comment]
![Discord_U0SG27AJwM](https://github.com/LuckFire/amoled-cord/assets/73630497/24933908-0b2c-46f7-8f99-454f7a278e91)

**Comment by Infisrael** [comment]
> Thanks, would've appreciated that if it was provided alongside the issue being opened. I'll see if i can get this fixed soon; Discord keeps booting me out whenever I open inspect so I can't do much atm (I saw a few other _new_ areas that could be themed as well).

I suggest you don't close it, I am finding stuff that is not amoled'd at the moment and posting it gradually here.

**Comment by FedeIlLeone** [comment]
Uhm, are you sure you aren't using some very old version of the theme?

**Comment by Infisrael** [comment]
No? I'm using the link for it (this repository's link basically)
If you changed it, I would like the new link.

**Comment by LuckFire** [comment]
What client mod are you using? It'd just be best to reinstall the theme. I didn't check before, but the screenshots you've sent are areas that have already been covered.

**Comment by Infisrael** [comment]
Nevermind, I'll just close the issue.

**Comment by LuckFire** [comment]
Very helpful.

**Comment by SlippingGitty** [comment]
> Nevermind, I'll just close the issue.

Hi, I am having the same issue. Did you by chance resolve this before closing it? Can you tell me what you did if so. Thanks in advance.
