### ISSUE TITLE
[UNTHEMED]: A ui box is not themed properly

### ISSUE THREAD

**Issue by Walianjin** [LuckFire/amoled-cord#70]
### Client Mod

Vencord

### Please provide screenshots of the unthemed areas.

<img width="432" alt="image" src="https://github.com/LuckFire/amoled-cord/assets/68111578/6d95b56d-8d05-4741-9607-3ad2e17c3c7a">

I believe the light grey line at the botom of the box should be at the top.
I used this custom css to fix that ui element on my client but I have no idea 
```
.container_ca50b9 {
  margin-top: 1px;
  margin-bottom: 0px;
}
```

### Before Submitting

- [X] I checked for similar reports of this issue.
- [X] I am on the latest stable Discord version.
- [X] I am on the latest version of the theme.
- [X] I have reinstalled the theme.

**Comment by LuckFire** [comment]
I am unable to replicate this. This is likely from some sort of plugin / theme / custom css that you have that adds a line to the bottom of the user area -- please check what plugin / theme / custom css modify the user area.

**Comment by Walianjin** [comment]
My bad.  Maybe it's a 1px gap that is very hard to see when not in full-screen mode with zoom level 200. I thought it was a misplaced divider. I have checked every plugin but the line is there anyway.

**Comment by LuckFire** [comment]
I had to use a color picker to even notice this since it was so hard to see. Windows already adds an outline to the application so it just made it wayyy harder to see with even whilst zoomed in.
