### ISSUE TITLE
[UNTHEMED]: channel and user list backdrops are not themed

### ISSUE THREAD

**Issue by inflz** [LuckFire/amoled-cord#73]
### Client Mod

BetterDiscord

### Please provide screenshots of the unthemed areas.

These were near black previously, but now are too bright.
![channel_1](https://github.com/LuckFire/amoled-cord/assets/34407148/6a240a7b-350b-4d82-992f-b7a8ad4bd915)
![channel_2](https://github.com/LuckFire/amoled-cord/assets/34407148/562c6dc7-1be7-4273-84dd-e9dfc157b64d)
![user](https://github.com/LuckFire/amoled-cord/assets/34407148/37b30bfd-0d51-4bf2-ae1f-fc03ca428f99)

### Before Submitting

- [X] I checked for similar reports of this issue.
- [X] I am on the latest stable Discord version.
- [X] I am on the latest version of the theme.
- [X] I have reinstalled the theme.

**Comment by LuckFire** [comment]
Thank you for reporting. Discord recently pushed an update that re-rolled classes. I'll have a fix pushed soon.
