### ISSUE TITLE
[UNTHEMED]: channel bar, dm bar and server user bar background unthemed

### ISSUE THREAD

**Issue by hedelmasalaatti** [LuckFire/amoled-cord#75]
### Client Mod

Vencord

### Please provide screenshots of the unthemed areas.

![channel bar](https://github.com/LuckFire/amoled-cord/assets/36992687/4da5c9cf-f094-462b-8a19-a6c69bfb1492)
![server user bar](https://github.com/LuckFire/amoled-cord/assets/36992687/b548b20c-7efb-49f9-b25b-8e81410724c4)
![dm bar](https://github.com/LuckFire/amoled-cord/assets/36992687/d2daf0da-3649-42e3-bc3c-b826bddeef5d)

before the change 15h ago they were as dark as the surroundings: 
![channel bar(old theme)](https://github.com/LuckFire/amoled-cord/assets/36992687/6e382b81-6b8d-4a14-9ab9-7a39ae878f48)
old screenshot taken using [this .css](https://raw.githubusercontent.com/LuckFire/amoled-cord/8ea13831eeec8754227d51db446dab38bb1476fd/clients/amoled-cord.theme.css)

### Before Submitting

- [X] I checked for similar reports of this issue.
- [X] I am on the latest stable Discord version.
- [X] I am on the latest version of the theme.
- [x] I have reinstalled the theme.

**Comment by mariospicross** [comment]
my girlfirend and i are also having this issue

**Comment by magizhchi99** [comment]
me too

**Comment by FairwellNoob** [comment]
Search bar produces same issue.
![JpVwXDq](https://github.com/LuckFire/amoled-cord/assets/79961729/f76e0041-5755-42d6-a82c-08606d9be237)
![G4mRwxB](https://github.com/LuckFire/amoled-cord/assets/79961729/71568f4c-8d75-408f-83cf-59595757571d)

**Comment by Viren070** [comment]
The emoji suggestion menu also has this issue.

![image](https://github.com/LuckFire/amoled-cord/assets/71220264/4af62f17-afbf-4b4a-9bac-ac6b02fb7b6b)

**Comment by Snowy404** [comment]
The member ping list also has this issue.
![image](https://github.com/LuckFire/amoled-cord/assets/65083757/7efa9224-0773-435c-a7c6-bd9c4f7768b8)

**Comment by VastHybrid** [comment]
I'm also getting the same issues. Wish discord would stop changing stuff and breaking themes.

**Comment by LuckFire** [comment]
It appears Discord decided to roll back the changes that initially broke everything. For the time being, this'll be monitored before a fix is pushed out; assuming Discord decides to completely roll it back, since it's still the same on the canary build.

**Comment by Roki100** [comment]
ty for fix ily @LuckFire

**Comment by LuckFire** [comment]
Reverted changes, should be fixed now
