### ISSUE TITLE
[UNTHEMED]: sidebars are not themed or are themed improperly in dms and servers

### ISSUE THREAD

**Issue by gr4veyxrd** [LuckFire/amoled-cord#77]
### Client Mod

Vencord, BetterDiscord

### Please provide screenshots of the unthemed areas.

![image](https://github.com/LuckFire/amoled-cord/assets/118139323/4695ca8a-aafc-43e5-88a9-e7322c6eeca6) ![image](https://github.com/LuckFire/amoled-cord/assets/118139323/039bca92-d8b9-4966-8117-aec810e961b5) 
![image](https://github.com/LuckFire/amoled-cord/assets/118139323/21009424-bd2d-4f6a-9660-3aad4bacb2f5)

it's done this once before, and it fixed itself. even after reinstalling betterdiscord, switching back to vencord, and reinstalling the theme on both, it's stayed like this. looks awful. i wish there was another person who maintained an amoled-like theme because this is the second time this has happened within a few months

### Before Submitting

- [X] I checked for similar reports of this issue.
- [X] I am on the latest stable Discord version.
- [X] I am on the latest version of the theme.
- [X] I have reinstalled the theme.

**Comment by LuckFire** [comment]
> i wish there was another person who maintained an amoled-like theme because this is the second time this has happened within a few months

Discord recently just pushed out an update that broke themes again; based on the announcement posted in Vencord, this was literally in the last 5-10 minutes, but it was probably a bit before that. This will be fixed soon, thanks for your patience.

**Comment by gr4veyxrd** [comment]
> Discord recently just pushed out an update that broke themes again; based on the announcement posted in Vencord, this was literally in the last 5-10 minutes, but it was probably a bit before that. This will be fixed soon, thanks for your patience.

thank you for the quick reply, apologies for the passive-aggressiveness in my report. i'm not present in any of the modded discord communities so i'm not typically up to date with issues.

**Comment by LuckFire** [comment]
It appears that Discord has pushed a previous build they initially reverted (which was the one that caused issues the first time, then was reverted after a fix was pushed) so I was able to use everything from that reverted commit. I'm not going to merge this for the time being until I review it a bit more and confirm that Discord won't just randomly roll back the build again.

**Comment by QuanTrieuPCYT** [comment]
Confirm this as well. Experiencing the same behavior after restarting my Vesktop instance

**Comment by gr4veyxrd** [comment]
Issue is back.

**Comment by LuckFire** [comment]
Discord pushed an update, which also seems to have broken a bunch of client mod functionality. Reopening this issue until theme issues are resolved.

**Comment by EthanWinters2885** [comment]
Yeah was going to mention this, I hope this will be fixed soon! Like always, take your time

**Comment by LuckFire** [comment]
Closing this issue, it makes more sense to refer to a new one so when a pr or commit is made, it can properly reference it.
New issue is #84.
