### ISSUE TITLE
[UNTHEMED]: An option for a semi translucent background

### ISSUE THREAD

**Issue by FormalSnake** [LuckFire/amoled-cord#79]
### Client Mod

Vencord

### Please provide screenshots of the unthemed areas.

Vencord has a transparent window with background blur, but this theme is all solid and it would be cool to have a branch with it being translucent

### Before Submitting

- [X] I checked for similar reports of this issue.
- [X] I am on the latest stable Discord version.
- [X] I am on the latest version of the theme.
- [X] I have reinstalled the theme.

**Comment by LuckFire** [comment]
Not worth the time or effort to do and maintain.
