### ISSUE TITLE
Remove userbg support

### ISSUE THREAD

**Issue by RadNotRed** [LuckFire/amoled-cord#8]
With the new header userbg breaks it completely and its not removable from the BD plugin from my knowledge 
![Discord_CLcHh32HC5](https://user-images.githubusercontent.com/80015713/120941101-dbf95a00-c6ee-11eb-81ad-6538d095257b.png)
everything gets moved downwards and you cant fix it

**Comment by LuckFire** [comment]
I've removed this in v2. Please make sure you redownload the theme entirely.
