### ISSUE TITLE
Game overlay becomes completely black and covers the screen.

### ISSUE THREAD

**Issue by Voideox** [LuckFire/amoled-cord#82]
### Client Mod

Vencord

### Please provide screenshots of the unthemed areas.

Over the last couple of days my in-game overlay has been turning fully black when using this theme, making it unusable. I have tested with no other themes or plugins (Vencord) and the behavior is consistent, so I can only assume it is an issue with a recent update of this theme.

### Before Submitting

- [X] I checked for similar reports of this issue.
- [X] I am on the latest stable Discord version.
- [X] I am on the latest version of the theme.
- [X] I have reinstalled the theme.

**Comment by LuckFire** [comment]
I would appreciate some screenshots of this. I haven't made any changes that I know would impact game overlays, especially when they have to be injected into separately. I'll also see if I can get it to reproduce on my end.

**Comment by Voideox** [comment]
I am able to consistently reproduce this issue on my end. I tried other themes to see if it would occur with them but this is not the case, so I am not sure where the problem lies. Let me know if there is any more information I can provide and I would be happy to.

https://www.youtube.com/watch?v=XKYYy4zp0HU

**Comment by LuckFire** [comment]
Thanks for reporting this! It appears that Discord has implemented something for overlays being themed and the way the experiment works is random.

I'll work on a fix for this and roll it soon.
