### ISSUE TITLE
[UNTHEMED]: Sidebar, Buttons, Titlebar, unknown BetterDiscord plugin settings category header text not themed

### ISSUE THREAD

**Issue by whataboutism-alos** [LuckFire/amoled-cord#84]
### Client Mod

BetterDiscord

### Please provide screenshots of the unthemed areas.

Believe the most recent discord update caused this, as it was previously fine. The above elements are all now way too bright, a gray rather than near-black - except in the last case, where text which is meant to be white is now black. That last one is really hard to see, you'll probably have to squint and lean in haha.
![amoled_instance1](https://github.com/LuckFire/amoled-cord/assets/90494794/61831660-420b-4b0f-bbcf-a2cca4d13fb4)
![amoled_instance2](https://github.com/LuckFire/amoled-cord/assets/90494794/488cb314-2c49-49d0-b32a-02dbd346a0c6)

### Before Submitting

- [X] I checked for similar reports of this issue.
- [X] I am on the latest stable Discord version.
- [X] I am on the latest version of the theme.
- [X] I have reinstalled the theme.

**Comment by FairwellNoob** [comment]
![image](https://github.com/LuckFire/amoled-cord/assets/79961729/a37f7ee3-1028-4847-b1ac-18680fda11eb)
Polls are also unthemed. I am using Vesktop's online themes.

**Comment by Hadock-is-ok** [comment]
I've made a pr (#84) with the new class names, hopefully @LuckFire can look over it soon and merge.
