### ISSUE TITLE
[UNTHEMED]: Discord's new "Full profiles" feature is not themed

### ISSUE THREAD

**Issue by FairwellNoob** [LuckFire/amoled-cord#87]
### Client Mod

Vesktop (Vencord Web)

### Please provide screenshots of the unthemed areas.

![image](https://github.com/LuckFire/amoled-cord/assets/79961729/009971ad-4c78-47cf-a51b-0f3214172c45)
Right click selected user (not yourself) > Click "Profile" OR Left click on selected user (not yourself) > click hamburger menu (More) > View Full Profile

### Before Submitting

- [X] I checked for similar reports of this issue.
- [X] I am on the latest stable Discord version.
- [X] I am on the latest version of the theme.
- [X] I have reinstalled the theme.

**Comment by FairwellNoob** [comment]
I am not sure if the mini profile is unthemed, I couldn't tell the difference
![image](https://github.com/LuckFire/amoled-cord/assets/79961729/076dd5df-1105-4893-ac52-9420c779324e)

**Comment by alessandromrc** [comment]
Same here.

**Comment by LuckFire** [comment]
Fixed in #89
