### ISSUE TITLE
[UNTHEMED]: When using search function, username is not themed

### ISSUE THREAD

**Issue by FairwellNoob** [LuckFire/amoled-cord#90]
### Client Mod

Vesktop

### Please provide screenshots of the unthemed areas.

![image](https://github.com/user-attachments/assets/47ccbae7-d8cd-4d01-831a-d3a2687d2064)

### Before Submitting

- [X] I checked for similar reports of this issue.
- [X] I am on the latest stable Discord version.
- [X] I am on the latest version of the theme.
- [X] I have reinstalled the theme.

**Comment by LuckFire** [comment]
It seems like this fixed itself since it is no longer occurring on my end either.
