### ISSUE TITLE
[UNTHEMED]: Top window bar, New DM Button, Side of application is not themed

### ISSUE THREAD

**Issue by vizionfox** [LuckFire/amoled-cord#92]
### Client Mod

Vencord

### Please provide screenshots of the unthemed areas.

There are a few areas unthemed with the new Discord client update
Client version:
stable 311885 (0ae8466) Host 1.0.9155 x64 (49817) Build Override: N/A Windows 11 64-bit (10.0.22631)
Vencord 80b493d (Standalone)
Electron 30.2.0
Chromium 124.0.6367.243

![image](https://github.com/user-attachments/assets/9e05d713-043a-42f3-a4d9-f38882910e42)

### Before Submitting

- [X] I checked for similar reports of this issue.
- [X] I am on the latest stable Discord version.
- [X] I am on the latest version of the theme.
- [X] I have reinstalled the theme.

**Comment by LuckFire** [comment]
You appear to have the new design, either because of eligibility or you have manually enabled it. It is advised to go into experiments and disable it if possible since I do not have plans on support AMOLED-cord with it until it is fully rolled out.

**Comment by vizionfox** [comment]
I can confirm I did have the Visual Refresh experiment enabled, I have disabled it and am back on the old design.
Thank you!
