### ISSUE TITLE
DM bar completely vanished

### ISSUE THREAD

**Issue by YeetusDeletus32** [LuckFire/amoled-cord#96]
### Client Mod

Vencord

### Please provide screenshots of the unthemed areas.

![Capture](https://github.com/user-attachments/assets/c439c9f6-a17f-4f32-8e10-32e15ec85bfd)

Hey!
Since today when I open discord I dont see my friends list for some reason.
I have checked it and the amoled cord theme looks to be the issue, everytime i activate it my friends list completely vanishes (blacked out) for some reason. The list is still there and I can click on my dms, but I just dont see them at all...
Reinstalling/repairing vencord, the amoled cord theme, discord itself all didnt do anything so I figured it has to be an issue with this theme.

### Before Submitting

- [X] I checked for similar reports of this issue.
- [X] I am on the latest stable Discord version.
- [X] I am on the latest version of the theme.
- [X] I have reinstalled the theme.

**Comment by YeetusDeletus32** [comment]
Thanks for fixing this so fast!

**Comment by Buttered-Alex** [comment]
Sorry, but is it actually fixed? I've uninstalled and reinstalled the theme and even uninstalled and reinstalled betterdiscord entirely but I still have this same issue

**Comment by YeetusDeletus32** [comment]
I cant tell, ive installed the updated one and it just started working for me...
